name: Deploy website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1.0.4
      
      - name: Assemble with Gradle
        run: ./gradlew :browserDistribution
        
      - uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: build/distributions

      - uses: actions/configure-pages@v2
      - uses: actions/setup-java@v3.4.1
        with:
          distribution: 'adopt'
          java-version: 11
          
      - run: ./gradlew build
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
